// @generated by vox-codegen
// DO NOT EDIT - regenerate with `cargo xtask codegen --typescript`

import type { Caller, MethodDescriptor, ServiceDescriptor, VoxCall, Dispatcher, RequestContext, SessionTransportOptions } from "@bearcove/vox-core";
import { session, voxServiceMetadata } from "@bearcove/vox-core";
import { wsConnector } from "@bearcove/vox-ws";
import { RpcError } from "@bearcove/vox-core";

// Named type definitions
export type FileStatus =
  | { tag: 'Modified' }
  | { tag: 'Added' }
  | { tag: 'Deleted' }
  | { tag: 'Renamed' }
  | { tag: 'Unchanged' }
  | { tag: 'Binary' };

export interface ReviewFile {
  path: string;
  old_path: string | null;
  status: FileStatus;
  is_changed: boolean;
  viewed: boolean;
  comment_count: number;
  added_lines: number;
  removed_lines: number;
}

export interface FileContent {
  old: string[] | null;
  new: string[] | null;
}

export interface LineRange {
  start: number;
  end: number;
}

export interface PairedRange {
  old: LineRange;
  new: LineRange;
}

export interface NewRange {
  new: LineRange;
}

export interface OldRange {
  old: LineRange;
}

export type DiffSection =
  | { tag: 'Context'; context: PairedRange }
  | { tag: 'Added'; added: NewRange }
  | { tag: 'Removed'; removed: OldRange };

export interface DiffHunk {
  old: LineRange | null;
  new: LineRange | null;
  sections: DiffSection[];
}

export interface FileDiff {
  path: string;
  hunks: DiffHunk[];
}

export interface ApiThreadAnchor {
  side: string | null;
  start_line: number | null;
  end_line: number | null;
}

export interface ApiReviewComment {
  id: string;
  author_name: string;
  author_kind: string;
  body: string;
  created_at: string;
  edited_at: string | null;
  can_edit: boolean;
}

export interface ApiCommentThread {
  id: string;
  scope: string;
  path: string | null;
  line_label: string;
  anchor: ApiThreadAnchor;
  resolved: boolean;
  comments: ApiReviewComment[];
}

export interface ApiCommit {
  oid: string;
  summary: string;
}

export interface ApiReviewPayload {
  review_id: string;
  target_label: string;
  is_branch_review: boolean;
  files: ReviewFile[];
  file_contents_by_path: Map<string, FileContent>;
  file_diffs_by_path: Map<string, FileDiff>;
  threads: ApiCommentThread[];
  review_threads: ApiCommentThread[];
  commits: ApiCommit[];
}

export type FileSide =
  | { tag: 'Old' }
  | { tag: 'New' };

export interface CreateThreadRequest {
  scope: string;
  path: string | null;
  side: FileSide | null;
  start_line: number | null;
  end_line: number | null;
  body: string;
}

export interface ThreadBodyRequest {
  thread_id: string;
  body: string;
}

export interface EditCommentRequest {
  comment_id: string;
  body: string;
}

export interface CommentRequest {
  comment_id: string;
}

export interface ThreadRequest {
  thread_id: string;
}

export interface MarkFileViewedRequest {
  path: string;
  viewed: boolean;
}

export interface SubmitReviewRequest {
  body: string | null;
}

// Request/Response type aliases
export type GetReviewRequest = [string];
export type GetReviewResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type RefreshDiffRequest = [string];
export type RefreshDiffResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type CreateThreadResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type ReplyToThreadRequest = [
  string, // token
  ThreadBodyRequest, // request
];
export type ReplyToThreadResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type EditCommentResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type DeleteCommentRequest = [
  string, // token
  CommentRequest, // request
];
export type DeleteCommentResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type DeleteThreadRequest = [
  string, // token
  ThreadRequest, // request
];
export type DeleteThreadResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type ResolveThreadRequest = [
  string, // token
  ThreadRequest, // request
];
export type ResolveThreadResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type ReopenThreadRequest = [
  string, // token
  ThreadRequest, // request
];
export type ReopenThreadResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type MarkFileViewedResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

export type SubmitReviewResponse = { ok: true; value: ApiReviewPayload } | { ok: false; error: string };

// Caller interface for PeersReview
export interface PeersReviewCaller {
  getReview(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  refreshDiff(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  createThread(token: string, request: CreateThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  replyToThread(token: string, request: ThreadBodyRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  editComment(token: string, request: EditCommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  deleteComment(token: string, request: CommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  deleteThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  resolveThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  reopenThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  markFileViewed(token: string, request: MarkFileViewedRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
  submitReview(token: string, request: SubmitReviewRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }>;
}

// Client implementation for PeersReview
export class PeersReviewClient implements PeersReviewCaller {
  private caller: Caller;

  constructor(caller: Caller) {
    this.caller = caller;
  }

  async getReview(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_getReview_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.getReview",
          args: { token },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async refreshDiff(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_refreshDiff_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.refreshDiff",
          args: { token },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async createThread(token: string, request: CreateThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_createThread_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.createThread",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async replyToThread(token: string, request: ThreadBodyRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_replyToThread_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.replyToThread",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async editComment(token: string, request: EditCommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_editComment_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.editComment",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async deleteComment(token: string, request: CommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_deleteComment_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.deleteComment",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async deleteThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_deleteThread_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.deleteThread",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async resolveThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_resolveThread_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.resolveThread",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async reopenThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_reopenThread_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.reopenThread",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async markFileViewed(token: string, request: MarkFileViewedRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_markFileViewed_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.markFileViewed",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

  async submitReview(token: string, request: SubmitReviewRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> {
    const descriptor = peersReview_submitReview_method;
    const sendSchemas = peersReview_descriptor.send_schemas;
      try {
        const value = await this.caller.call({
          method: "PeersReview.submitReview",
          args: { token, request },
          descriptor,
          sendSchemas,
        });
        return { ok: true, value } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
      } catch (e: any) {
        if (e instanceof RpcError && e.isUserError()) {
          return { ok: false, error: e.userError } as { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
        }
        throw e;
      }
  }

}

/**
 * Connect to a PeersReview server over WebSocket.
 * @param url - WebSocket URL (e.g., "ws://localhost:9000")
 * @returns A connected PeersReviewClient instance
 */
export async function connectPeersReview(
  url: string,
  options: SessionTransportOptions = {},
): Promise<PeersReviewClient> {
  const established = await session.initiator(wsConnector(url), { ...options, metadata: voxServiceMetadata("PeersReview") });
  return new PeersReviewClient(established.rootConnection().caller());
}

// Handler interface for PeersReview
export interface PeersReviewHandler {
  getReview(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  refreshDiff(token: string): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  createThread(token: string, request: CreateThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  replyToThread(token: string, request: ThreadBodyRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  editComment(token: string, request: EditCommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  deleteComment(token: string, request: CommentRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  deleteThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  resolveThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  reopenThread(token: string, request: ThreadRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  markFileViewed(token: string, request: MarkFileViewedRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
  submitReview(token: string, request: SubmitReviewRequest): Promise<{ ok: true; value: ApiReviewPayload } | { ok: false; error: string }> | { ok: true; value: ApiReviewPayload } | { ok: false; error: string };
}

// Dispatcher for PeersReview
export class PeersReviewDispatcher implements Dispatcher {
  private readonly handler: PeersReviewHandler;

  constructor(handler: PeersReviewHandler) {
    this.handler = handler;
  }

  getDescriptor(): ServiceDescriptor {
    return peersReview_descriptor;
  }

  async dispatch(_context: RequestContext, method: MethodDescriptor, args: unknown[], call: VoxCall): Promise<void> {
    if (method.id === 0xa744d74a9d4feccan) {
      try {
        const result = await this.handler.getReview(args[0] as string);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0xd5a6f04da6d80aden) {
      try {
        const result = await this.handler.refreshDiff(args[0] as string);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x0232da353c47a76cn) {
      try {
        const result = await this.handler.createThread(args[0] as string, args[1] as CreateThreadRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0xd98f694a3ac8ad18n) {
      try {
        const result = await this.handler.replyToThread(args[0] as string, args[1] as ThreadBodyRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x548fdb37a03112f6n) {
      try {
        const result = await this.handler.editComment(args[0] as string, args[1] as EditCommentRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0xa179c6d44322d169n) {
      try {
        const result = await this.handler.deleteComment(args[0] as string, args[1] as CommentRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x2957abe705eead68n) {
      try {
        const result = await this.handler.deleteThread(args[0] as string, args[1] as ThreadRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x2084205f40994867n) {
      try {
        const result = await this.handler.resolveThread(args[0] as string, args[1] as ThreadRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x0432302f2d35202dn) {
      try {
        const result = await this.handler.reopenThread(args[0] as string, args[1] as ThreadRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x1baa8d31a1c77d47n) {
      try {
        const result = await this.handler.markFileViewed(args[0] as string, args[1] as MarkFileViewedRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    } else if (method.id === 0x2d2df1e3ed688811n) {
      try {
        const result = await this.handler.submitReview(args[0] as string, args[1] as SubmitReviewRequest);
        if (result.ok) call.reply(result.value); else call.replyErr(result.error);
      } catch (error) {
        call.replyInternalError(error instanceof Error ? error.message : String(error));
      }
    }
  }
}

// Schema objects for wire schema exchange (TypeScript → Rust)
// Generated from Rust Facet shapes — do not modify.
export const peersReview_send_schemas: import("@bearcove/vox-core").ServiceSendSchemas = {
  schemas: new Map<bigint, import("@bearcove/vox-postcard").Schema>([
    [0x178367a87f66fb46n, { id: 0x178367a87f66fb46n, type_params: [], kind: { tag: 'primitive', primitive_type: 'bool' } }],
    [0x281c5be4f2ee63b4n, { id: 0x281c5be4f2ee63b4n, type_params: [], kind: { tag: 'primitive', primitive_type: 'u32' } }],
    [0x42046de663beeef0n, { id: 0x42046de663beeef0n, type_params: ['T', 'E'], kind: { tag: 'enum', name: 'Result', variants: [{ name: 'Ok', index: 0, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'T' } } }, { name: 'Err', index: 1, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'E' } } }] } }],
    [0x5db70a394660f3e6n, { id: 0x5db70a394660f3e6n, type_params: [], kind: { tag: 'primitive', primitive_type: 'never' } }],
    [0x6d7dce914ee150e8n, { id: 0x6d7dce914ee150e8n, type_params: [], kind: { tag: 'primitive', primitive_type: 'string' } }],
    [0x4cf4b2aeb98a1939n, { id: 0x4cf4b2aeb98a1939n, type_params: ['E'], kind: { tag: 'enum', name: 'VoxError', variants: [{ name: 'User', index: 0, payload: { tag: 'newtype', type_ref: { tag: 'var', name: 'E' } } }, { name: 'UnknownMethod', index: 1, payload: { tag: 'unit' } }, { name: 'InvalidPayload', index: 2, payload: { tag: 'newtype', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] } } }, { name: 'Cancelled', index: 3, payload: { tag: 'unit' } }, { name: 'ConnectionClosed', index: 4, payload: { tag: 'unit' } }, { name: 'SessionShutdown', index: 5, payload: { tag: 'unit' } }, { name: 'SendFailed', index: 6, payload: { tag: 'unit' } }, { name: 'Indeterminate', index: 7, payload: { tag: 'unit' } }] } }],
    [0x6847ab90feda71c1n, { id: 0x6847ab90feda71c1n, type_params: ['T0'], kind: { tag: 'tuple', elements: [{ tag: 'var', name: 'T0' }] } }],
    [0xdcafd4de6b7969bbn, { id: 0xdcafd4de6b7969bbn, type_params: ['T'], kind: { tag: 'option', element: { tag: 'var', name: 'T' } } }],
    [0x1d0b7f84d01e5c39n, { id: 0x1d0b7f84d01e5c39n, type_params: [], kind: { tag: 'enum', name: 'FileStatus', variants: [{ name: 'Modified', index: 0, payload: { tag: 'unit' } }, { name: 'Added', index: 1, payload: { tag: 'unit' } }, { name: 'Deleted', index: 2, payload: { tag: 'unit' } }, { name: 'Renamed', index: 3, payload: { tag: 'unit' } }, { name: 'Unchanged', index: 4, payload: { tag: 'unit' } }, { name: 'Binary', index: 5, payload: { tag: 'unit' } }] } }],
    [0xb02b01faff3dcd5cn, { id: 0xb02b01faff3dcd5cn, type_params: [], kind: { tag: 'struct', name: 'ReviewFile', fields: [{ name: 'path', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'old_path', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }, { name: 'status', type_ref: { tag: 'concrete', type_id: 0x1d0b7f84d01e5c39n, args: [] }, required: true }, { name: 'is_changed', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }, { name: 'viewed', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }, { name: 'comment_count', type_ref: { tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true }, { name: 'added_lines', type_ref: { tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true }, { name: 'removed_lines', type_ref: { tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true }] } }],
    [0x0a96b404b4d79d67n, { id: 0x0a96b404b4d79d67n, type_params: ['T'], kind: { tag: 'list', element: { tag: 'var', name: 'T' } } }],
    [0x0cc4f73ac3531f6dn, { id: 0x0cc4f73ac3531f6dn, type_params: [], kind: { tag: 'struct', name: 'FileContent', fields: [{ name: 'old', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] }, required: true }, { name: 'new', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] }, required: true }] } }],
    [0xd2090ac76e20f7e9n, { id: 0xd2090ac76e20f7e9n, type_params: ['K', 'V'], kind: { tag: 'map', key: { tag: 'var', name: 'K' }, value: { tag: 'var', name: 'V' } } }],
    [0x303e1552e4e3bf7an, { id: 0x303e1552e4e3bf7an, type_params: [], kind: { tag: 'struct', name: 'LineRange', fields: [{ name: 'start', type_ref: { tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true }, { name: 'end', type_ref: { tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }, required: true }] } }],
    [0x9d013f25bbf3fd17n, { id: 0x9d013f25bbf3fd17n, type_params: [], kind: { tag: 'struct', name: 'PairedRange', fields: [{ name: 'old', type_ref: { tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }, required: true }, { name: 'new', type_ref: { tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }, required: true }] } }],
    [0x838d35b563fce316n, { id: 0x838d35b563fce316n, type_params: [], kind: { tag: 'struct', name: 'NewRange', fields: [{ name: 'new', type_ref: { tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }, required: true }] } }],
    [0x97e0306cd61f69b9n, { id: 0x97e0306cd61f69b9n, type_params: [], kind: { tag: 'struct', name: 'OldRange', fields: [{ name: 'old', type_ref: { tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }, required: true }] } }],
    [0xd0eee227c0f16702n, { id: 0xd0eee227c0f16702n, type_params: [], kind: { tag: 'enum', name: 'DiffSection', variants: [{ name: 'Context', index: 0, payload: { tag: 'struct', fields: [{ name: 'context', type_ref: { tag: 'concrete', type_id: 0x9d013f25bbf3fd17n, args: [] }, required: true }] } }, { name: 'Added', index: 1, payload: { tag: 'struct', fields: [{ name: 'added', type_ref: { tag: 'concrete', type_id: 0x838d35b563fce316n, args: [] }, required: true }] } }, { name: 'Removed', index: 2, payload: { tag: 'struct', fields: [{ name: 'removed', type_ref: { tag: 'concrete', type_id: 0x97e0306cd61f69b9n, args: [] }, required: true }] } }] } }],
    [0x55e1ba816502b1b0n, { id: 0x55e1ba816502b1b0n, type_params: [], kind: { tag: 'struct', name: 'DiffHunk', fields: [{ name: 'old', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }] }, required: true }, { name: 'new', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x303e1552e4e3bf7an, args: [] }] }, required: true }, { name: 'sections', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xd0eee227c0f16702n, args: [] }] }, required: true }] } }],
    [0x00948c0df63c1a01n, { id: 0x00948c0df63c1a01n, type_params: [], kind: { tag: 'struct', name: 'FileDiff', fields: [{ name: 'path', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'hunks', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0x55e1ba816502b1b0n, args: [] }] }, required: true }] } }],
    [0xaf66cc6f4de6af5an, { id: 0xaf66cc6f4de6af5an, type_params: [], kind: { tag: 'struct', name: 'ApiThreadAnchor', fields: [{ name: 'side', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }, { name: 'start_line', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }] }, required: true }, { name: 'end_line', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }] }, required: true }] } }],
    [0xda9807692e9b64b3n, { id: 0xda9807692e9b64b3n, type_params: [], kind: { tag: 'struct', name: 'ApiReviewComment', fields: [{ name: 'id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'author_name', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'author_kind', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'body', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'created_at', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'edited_at', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }, { name: 'can_edit', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }] } }],
    [0xf480e182ef0815f5n, { id: 0xf480e182ef0815f5n, type_params: [], kind: { tag: 'struct', name: 'ApiCommentThread', fields: [{ name: 'id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'scope', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'path', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }, { name: 'line_label', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'anchor', type_ref: { tag: 'concrete', type_id: 0xaf66cc6f4de6af5an, args: [] }, required: true }, { name: 'resolved', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }, { name: 'comments', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xda9807692e9b64b3n, args: [] }] }, required: true }] } }],
    [0x760638aaadca4400n, { id: 0x760638aaadca4400n, type_params: [], kind: { tag: 'struct', name: 'ApiCommit', fields: [{ name: 'oid', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'summary', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0x8d30dce9bc2af470n, { id: 0x8d30dce9bc2af470n, type_params: [], kind: { tag: 'struct', name: 'ApiReviewPayload', fields: [{ name: 'review_id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'target_label', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'is_branch_review', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }, { name: 'files', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xb02b01faff3dcd5cn, args: [] }] }, required: true }, { name: 'file_contents_by_path', type_ref: { tag: 'concrete', type_id: 0xd2090ac76e20f7e9n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x0cc4f73ac3531f6dn, args: [] }] }, required: true }, { name: 'file_diffs_by_path', type_ref: { tag: 'concrete', type_id: 0xd2090ac76e20f7e9n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x00948c0df63c1a01n, args: [] }] }, required: true }, { name: 'threads', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xf480e182ef0815f5n, args: [] }] }, required: true }, { name: 'review_threads', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0xf480e182ef0815f5n, args: [] }] }, required: true }, { name: 'commits', type_ref: { tag: 'concrete', type_id: 0x0a96b404b4d79d67n, args: [{ tag: 'concrete', type_id: 0x760638aaadca4400n, args: [] }] }, required: true }] } }],
    [0xdddb435492d4bfd9n, { id: 0xdddb435492d4bfd9n, type_params: [], kind: { tag: 'enum', name: 'FileSide', variants: [{ name: 'Old', index: 0, payload: { tag: 'unit' } }, { name: 'New', index: 1, payload: { tag: 'unit' } }] } }],
    [0xc35b49af6d0da0fcn, { id: 0xc35b49af6d0da0fcn, type_params: [], kind: { tag: 'struct', name: 'CreateThreadRequest', fields: [{ name: 'scope', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'path', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }, { name: 'side', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0xdddb435492d4bfd9n, args: [] }] }, required: true }, { name: 'start_line', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }] }, required: true }, { name: 'end_line', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x281c5be4f2ee63b4n, args: [] }] }, required: true }, { name: 'body', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0xba0496aa8cee7a4cn, { id: 0xba0496aa8cee7a4cn, type_params: ['T0', 'T1'], kind: { tag: 'tuple', elements: [{ tag: 'var', name: 'T0' }, { tag: 'var', name: 'T1' }] } }],
    [0x82e1acaf19080929n, { id: 0x82e1acaf19080929n, type_params: [], kind: { tag: 'struct', name: 'ThreadBodyRequest', fields: [{ name: 'thread_id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'body', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0xde9b14585005eddbn, { id: 0xde9b14585005eddbn, type_params: [], kind: { tag: 'struct', name: 'EditCommentRequest', fields: [{ name: 'comment_id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'body', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0x2f01e891755fde36n, { id: 0x2f01e891755fde36n, type_params: [], kind: { tag: 'struct', name: 'CommentRequest', fields: [{ name: 'comment_id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0x9af4fdb77e8dfe04n, { id: 0x9af4fdb77e8dfe04n, type_params: [], kind: { tag: 'struct', name: 'ThreadRequest', fields: [{ name: 'thread_id', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }] } }],
    [0x2b9986f589449c24n, { id: 0x2b9986f589449c24n, type_params: [], kind: { tag: 'struct', name: 'MarkFileViewedRequest', fields: [{ name: 'path', type_ref: { tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, required: true }, { name: 'viewed', type_ref: { tag: 'concrete', type_id: 0x178367a87f66fb46n, args: [] }, required: true }] } }],
    [0x1d158c792f9f384an, { id: 0x1d158c792f9f384an, type_params: [], kind: { tag: 'struct', name: 'SubmitReviewRequest', fields: [{ name: 'body', type_ref: { tag: 'concrete', type_id: 0xdcafd4de6b7969bbn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, required: true }] } }],
  ]),
  methods: new Map<bigint, import("@bearcove/vox-core").MethodSendSchemas>([
    [0xa744d74a9d4feccan, { argsRootRef: { tag: 'concrete', type_id: 0x6847ab90feda71c1n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0xd5a6f04da6d80aden, { argsRootRef: { tag: 'concrete', type_id: 0x6847ab90feda71c1n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x0232da353c47a76cn, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0xc35b49af6d0da0fcn, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0xd98f694a3ac8ad18n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x82e1acaf19080929n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x548fdb37a03112f6n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0xde9b14585005eddbn, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0xa179c6d44322d169n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x2f01e891755fde36n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x2957abe705eead68n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x9af4fdb77e8dfe04n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x2084205f40994867n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x9af4fdb77e8dfe04n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x0432302f2d35202dn, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x9af4fdb77e8dfe04n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x1baa8d31a1c77d47n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x2b9986f589449c24n, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
    [0x2d2df1e3ed688811n, { argsRootRef: { tag: 'concrete', type_id: 0xba0496aa8cee7a4cn, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }, { tag: 'concrete', type_id: 0x1d158c792f9f384an, args: [] }] }, responseRootRef: { tag: 'concrete', type_id: 0x42046de663beeef0n, args: [{ tag: 'concrete', type_id: 0x8d30dce9bc2af470n, args: [] }, { tag: 'concrete', type_id: 0x4cf4b2aeb98a1939n, args: [{ tag: 'concrete', type_id: 0x6d7dce914ee150e8n, args: [] }] }] } }],
  ]),
};

export const peersReview_getReview_method: MethodDescriptor = {
  name: 'getReview',
  id: 0xa744d74a9d4feccan,
  retry: { persist: false, idem: false },
};

export const peersReview_refreshDiff_method: MethodDescriptor = {
  name: 'refreshDiff',
  id: 0xd5a6f04da6d80aden,
  retry: { persist: false, idem: false },
};

export const peersReview_createThread_method: MethodDescriptor = {
  name: 'createThread',
  id: 0x0232da353c47a76cn,
  retry: { persist: false, idem: false },
};

export const peersReview_replyToThread_method: MethodDescriptor = {
  name: 'replyToThread',
  id: 0xd98f694a3ac8ad18n,
  retry: { persist: false, idem: false },
};

export const peersReview_editComment_method: MethodDescriptor = {
  name: 'editComment',
  id: 0x548fdb37a03112f6n,
  retry: { persist: false, idem: false },
};

export const peersReview_deleteComment_method: MethodDescriptor = {
  name: 'deleteComment',
  id: 0xa179c6d44322d169n,
  retry: { persist: false, idem: false },
};

export const peersReview_deleteThread_method: MethodDescriptor = {
  name: 'deleteThread',
  id: 0x2957abe705eead68n,
  retry: { persist: false, idem: false },
};

export const peersReview_resolveThread_method: MethodDescriptor = {
  name: 'resolveThread',
  id: 0x2084205f40994867n,
  retry: { persist: false, idem: false },
};

export const peersReview_reopenThread_method: MethodDescriptor = {
  name: 'reopenThread',
  id: 0x0432302f2d35202dn,
  retry: { persist: false, idem: false },
};

export const peersReview_markFileViewed_method: MethodDescriptor = {
  name: 'markFileViewed',
  id: 0x1baa8d31a1c77d47n,
  retry: { persist: false, idem: false },
};

export const peersReview_submitReview_method: MethodDescriptor = {
  name: 'submitReview',
  id: 0x2d2df1e3ed688811n,
  retry: { persist: false, idem: false },
};

// Service descriptor for runtime dispatch metadata
export const peersReview_descriptor: ServiceDescriptor = {
  service_name: 'PeersReview',
  send_schemas: peersReview_send_schemas,
  methods: new Map<bigint, MethodDescriptor>([
    [peersReview_getReview_method.id, peersReview_getReview_method],
    [peersReview_refreshDiff_method.id, peersReview_refreshDiff_method],
    [peersReview_createThread_method.id, peersReview_createThread_method],
    [peersReview_replyToThread_method.id, peersReview_replyToThread_method],
    [peersReview_editComment_method.id, peersReview_editComment_method],
    [peersReview_deleteComment_method.id, peersReview_deleteComment_method],
    [peersReview_deleteThread_method.id, peersReview_deleteThread_method],
    [peersReview_resolveThread_method.id, peersReview_resolveThread_method],
    [peersReview_reopenThread_method.id, peersReview_reopenThread_method],
    [peersReview_markFileViewed_method.id, peersReview_markFileViewed_method],
    [peersReview_submitReview_method.id, peersReview_submitReview_method],
  ]),
};

